/* Configuration file for wf-data-server-js

    DO NOT EDIT THIS FILE!

    Instead, copy it to config.js, then edit the copy:

    cp config-sample.js config.js
    nano config.js

*/

module.exports = {
    "mqtt": {
        "broker": "mqtt://localhost",
        "topicPattern": "nmea/+/+"
    },
    "database": {
        "path": "test_data.db"
    },
    "server": {
        "port": 3001
    },
    "accumulation": {
        // Time period in milliseconds to accumulate data before writing to the database
        "periodMs": 60000
    }
};


